[workspace]
members = [
    "bin/gemi-debugger",
    "bin/gemi-player",
    "bin/wasm-player",
    "lib/core",
    "tests/gen",
    "tests/shared",
    "tests/test_suite",
    "tests/update_test_report",
]
