[workspace]
resolver = "2"
members = [
    "bin/gemi-debugger",
    "bin/gemi-player",
    "bin/wasm-player",
    "lib",
    "lib/core",
    "lib/support",
    "lib/utils",
    "tests/gen",
    "tests/shared",
    "tests/test_nostd",
    "tests/test_suite",
    "tests/update_test_report",
]
