[package]
name = "gbemu"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dependencies.gbemu-core]
path = "../../lib/core"

[dependencies.sdl2]
version = "0.35.2"
features = ["bundled", "static-link", "unsafe_textures"]
