[package]
name = "gemi-debugger"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = { version = "0.4.38", features = ["serde"] }
eframe = { version = "0.27.2", default-features = false, features = [ "default_fonts", "glow", "persistence", ] }
egui = { version = "0.27.2", default-features = false }
egui_extras = "0.27.2"
egui_tiles = "0.8.0"
egui-modal = "0.3.5"
lazy_static = "1.4.0"
rfd = "0.14.1"
serde = "1.0.205"

# desktop:
[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
futures = "0.3.30"

# wasm:
[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-futures = "0.4"


[dependencies.gemi-core]
path = "../../lib/core"
features = ["snapshots"]

[dependencies.gemi-utils]
path = "../../lib/utils"

