[package]
name = "wasm-player"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = [ "cdylib", "rlib" ]

[dependencies]
wasm-bindgen = "0.2.87"

[dependencies.web-sys]
version = "0.3.64"
features = [
    "CanvasRenderingContext2d",
    "HtmlElement",
    "HtmlCanvasElement",
    "ImageData",
]

[dependencies.gemi-core]
path = "../../lib/core"

[dependencies.gemi-utils]
path = "../../lib/utils"
