[package]
name = "testrunner"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
image = "0.24.3"

[dependencies.gbemu-core]
path = "../lib/core"

[build-dependencies]
reqwest = { version = "0.11.12", features = ["blocking"] }
zip-extract = "0.1.1"
